/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TokenCreationResult = {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
        canisterId: string;
    };
};
export type VerifyPaymentResult = {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
    };
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentRecord {
    verified: boolean;
    usedForToken: boolean;
    treasuryAddressUsed: string;
    errorMessage?: string;
    tokenSymbol?: string;
    timestamp: Time;
    payer: Principal;
    amount: bigint;
}
export interface TokenConfig {
    status: TokenStatus;
    emblemAspectRatio?: bigint;
    decimals: bigint;
    featured: boolean;
    thumbnailUrl: string;
    creatorProfileUrl: string;
    circulatingSupply: bigint;
    tokenAddress?: string;
    name: string;
    tags: Array<string>;
    communityExplorer: boolean;
    treasuryFee: TreasuryFeeConfig;
    emblemProcessingMetadata?: EmblemProcessingMetadata;
    description: string;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    customFields: Array<CustomField>;
    validationTimestamp?: Time;
    testingStatus?: TestingStatus;
    paymentId?: bigint;
    taxModules: TaxModules;
    mediaType: MediaType;
    chartUrl: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<ModuleConfig>;
    rewardTokenAddress?: string;
    symbol: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface EmblemProcessingMetadata {
    originalWidth: bigint;
    cropWidth: bigint;
    originalHeight: bigint;
    cropX: bigint;
    cropY: bigint;
    processedAt: Time;
    cropHeight: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface TreasuryFeeConfig {
    enabled: boolean;
    sellFee: bigint;
    treasuryAddress: string;
    buyFee: bigint;
}
export interface TokenMetadata {
    status: TokenStatus;
    emblemAspectRatio?: bigint;
    popularityScore: bigint;
    creator: Principal;
    decimals: bigint;
    verified: boolean;
    featured: boolean;
    thumbnailUrl: string;
    fixedTreasuryFee: bigint;
    totalSellTax: bigint;
    creatorProfileUrl: string;
    views: bigint;
    circulatingSupply: bigint;
    deployedAt: Time;
    tokenAddress?: string;
    developerWalletWhitelisted: boolean;
    name: string;
    createdAt: Time;
    tags: Array<string>;
    trendingScore: bigint;
    communityExplorer: boolean;
    lastUpdated: Time;
    treasuryFee: bigint;
    emblemProcessingMetadata?: EmblemProcessingMetadata;
    description: string;
    mintFeePaid: boolean;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    likes: bigint;
    version: bigint;
    customFields: Array<CustomField>;
    sellTax: bigint;
    validationTimestamp?: Time;
    testingStatus?: TestingStatus;
    paymentId?: bigint;
    totalBuyTax: bigint;
    taxModules: TaxModules;
    auditStatus: AuditStatus;
    mediaType: MediaType;
    liquidityBurnAddress: string;
    chartUrl: string;
    comments: Array<Comment>;
    treasuryAddress: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<ModuleConfig>;
    buyTax: bigint;
    rewardTokenAddress?: string;
    symbol: string;
    canisterId: Principal;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Comment {
    content: string;
    authorName: string;
    author: Principal;
    timestamp: Time;
    authorProfileUrl: string;
}
export type PaymentResult = {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
        paymentId: bigint;
    };
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface GlobalPlatformStats {
    totalSupplyAcrossTokens: bigint;
    totalTokensCreated: bigint;
    platformTreasuryFees: bigint;
    totalUsers: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ModuleConfig {
    moduleType: ModuleType;
    tokenAddress?: string;
    reflectionTarget?: Principal;
    split: boolean;
    sellTax: bigint;
    unified: boolean;
    buyTax: bigint;
    rewardTokenAddress?: string;
}
export interface UserActivityMetrics {
    tokensMinted: bigint;
    totalFeesPaid: bigint;
    treasuryConfigurations: bigint;
    deploymentHistory: Array<string>;
}
export interface CustomField {
    key: string;
    value: string;
}
export interface TaxModules {
    support: boolean;
    burn: boolean;
    liquidity: boolean;
    reflection: boolean;
    yield: boolean;
    treasury: boolean;
}
export interface UserProfile {
    username: string;
    name: string;
    email: string;
    linkedPrincipals: Array<Principal>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AuditStatus {
    pending = "pending",
    approved = "approved",
    inReview = "inReview",
    rejected = "rejected"
}
export enum MediaType {
    gif = "gif",
    audio = "audio",
    video = "video",
    image = "image",
    unknown_ = "unknown"
}
export enum ModuleType {
    support = "support",
    burn = "burn",
    liquidity = "liquidity",
    reflection = "reflection",
    yield_ = "yield",
    treasury = "treasury"
}
export enum TestingStatus {
    inProgress = "inProgress",
    failed = "failed",
    passed = "passed"
}
export enum TokenStatus {
    active = "active",
    pending = "pending",
    inactive = "inactive",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createToken(config: TokenConfig): Promise<TokenCreationResult>;
    getAllTokens(): Promise<Array<TokenMetadata>>;
    getBuyMeACoffeeAddress(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCreationFee(): Promise<bigint>;
    getForgedTokens(): Promise<Array<TokenMetadata>>;
    getGlobalPlatformStats(): Promise<GlobalPlatformStats>;
    getPaymentRecord(paymentId: bigint): Promise<PaymentRecord | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getToken(symbol: string): Promise<TokenMetadata | null>;
    getTokenCount(): Promise<bigint>;
    getTreasuryAddress(): Promise<string>;
    getUserActivityMetrics(): Promise<UserActivityMetrics>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    lookupToken(canisterId: string): Promise<TokenMetadata | null>;
    markMintFeePaid(symbol: string, paymentId: bigint): Promise<void>;
    recordPayment(amount: bigint, treasuryAddress: string): Promise<PaymentResult>;
    registerToken(metadata: TokenMetadata): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    verifyPaymentWithLedger(transactionId: string, paymentId: bigint): Promise<VerifyPaymentResult>;
}
import type { AuditStatus as _AuditStatus, Comment as _Comment, CustomField as _CustomField, EmblemProcessingMetadata as _EmblemProcessingMetadata, MediaType as _MediaType, ModuleConfig as _ModuleConfig, ModuleType as _ModuleType, PaymentRecord as _PaymentRecord, PaymentResult as _PaymentResult, StripeSessionStatus as _StripeSessionStatus, TaxModules as _TaxModules, TestingStatus as _TestingStatus, Time as _Time, TokenConfig as _TokenConfig, TokenCreationResult as _TokenCreationResult, TokenMetadata as _TokenMetadata, TokenStatus as _TokenStatus, TreasuryFeeConfig as _TreasuryFeeConfig, UserProfile as _UserProfile, UserRole as _UserRole, VerifyPaymentResult as _VerifyPaymentResult, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createToken(arg0: TokenConfig): Promise<TokenCreationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createToken(to_candid_TokenConfig_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TokenCreationResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createToken(to_candid_TokenConfig_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TokenCreationResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTokens(): Promise<Array<TokenMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTokens();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTokens();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyMeACoffeeAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyMeACoffeeAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyMeACoffeeAddress();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreationFee(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreationFee();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreationFee();
            return result;
        }
    }
    async getForgedTokens(): Promise<Array<TokenMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForgedTokens();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForgedTokens();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalPlatformStats(): Promise<GlobalPlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalPlatformStats();
            return result;
        }
    }
    async getPaymentRecord(arg0: bigint): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentRecord(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentRecord(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToken(arg0: string): Promise<TokenMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getToken(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToken(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenCount();
            return result;
        }
    }
    async getTreasuryAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasuryAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasuryAddress();
            return result;
        }
    }
    async getUserActivityMetrics(): Promise<UserActivityMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivityMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivityMetrics();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async lookupToken(arg0: string): Promise<TokenMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupToken(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupToken(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMintFeePaid(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMintFeePaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMintFeePaid(arg0, arg1);
            return result;
        }
    }
    async recordPayment(arg0: bigint, arg1: string): Promise<PaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1);
                return from_candid_PaymentResult_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1);
            return from_candid_PaymentResult_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerToken(arg0: TokenMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerToken(to_candid_TokenMetadata_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerToken(to_candid_TokenMetadata_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async verifyPaymentWithLedger(arg0: string, arg1: bigint): Promise<VerifyPaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPaymentWithLedger(arg0, arg1);
                return from_candid_VerifyPaymentResult_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPaymentWithLedger(arg0, arg1);
            return from_candid_VerifyPaymentResult_n62(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuditStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditStatus): AuditStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleConfig_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleConfig): ModuleConfig {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleType): ModuleType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentResult_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentResult): PaymentResult {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TestingStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestingStatus): TestingStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TokenCreationResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenCreationResult): TokenCreationResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TokenMetadata_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenMetadata): TokenMetadata {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TokenStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenStatus): TokenStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyPaymentResult_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyPaymentResult): VerifyPaymentResult {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmblemProcessingMetadata]): EmblemProcessingMetadata | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestingStatus]): TestingStatus | null {
    return value.length === 0 ? null : from_candid_TestingStatus_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TokenMetadata]): TokenMetadata | null {
    return value.length === 0 ? null : from_candid_TokenMetadata_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TokenStatus;
    emblemAspectRatio: [] | [bigint];
    popularityScore: bigint;
    creator: Principal;
    decimals: bigint;
    verified: boolean;
    featured: boolean;
    thumbnailUrl: string;
    fixedTreasuryFee: bigint;
    totalSellTax: bigint;
    creatorProfileUrl: string;
    views: bigint;
    circulatingSupply: bigint;
    deployedAt: _Time;
    tokenAddress: [] | [string];
    developerWalletWhitelisted: boolean;
    name: string;
    createdAt: _Time;
    tags: Array<string>;
    trendingScore: bigint;
    communityExplorer: boolean;
    lastUpdated: _Time;
    treasuryFee: bigint;
    emblemProcessingMetadata: [] | [_EmblemProcessingMetadata];
    description: string;
    mintFeePaid: boolean;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    likes: bigint;
    version: bigint;
    customFields: Array<_CustomField>;
    sellTax: bigint;
    validationTimestamp: [] | [_Time];
    testingStatus: [] | [_TestingStatus];
    paymentId: [] | [bigint];
    totalBuyTax: bigint;
    taxModules: _TaxModules;
    auditStatus: _AuditStatus;
    mediaType: _MediaType;
    liquidityBurnAddress: string;
    chartUrl: string;
    comments: Array<_Comment>;
    treasuryAddress: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<_ModuleConfig>;
    buyTax: bigint;
    rewardTokenAddress: [] | [string];
    symbol: string;
    canisterId: Principal;
}): {
    status: TokenStatus;
    emblemAspectRatio?: bigint;
    popularityScore: bigint;
    creator: Principal;
    decimals: bigint;
    verified: boolean;
    featured: boolean;
    thumbnailUrl: string;
    fixedTreasuryFee: bigint;
    totalSellTax: bigint;
    creatorProfileUrl: string;
    views: bigint;
    circulatingSupply: bigint;
    deployedAt: Time;
    tokenAddress?: string;
    developerWalletWhitelisted: boolean;
    name: string;
    createdAt: Time;
    tags: Array<string>;
    trendingScore: bigint;
    communityExplorer: boolean;
    lastUpdated: Time;
    treasuryFee: bigint;
    emblemProcessingMetadata?: EmblemProcessingMetadata;
    description: string;
    mintFeePaid: boolean;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    likes: bigint;
    version: bigint;
    customFields: Array<CustomField>;
    sellTax: bigint;
    validationTimestamp?: Time;
    testingStatus?: TestingStatus;
    paymentId?: bigint;
    totalBuyTax: bigint;
    taxModules: TaxModules;
    auditStatus: AuditStatus;
    mediaType: MediaType;
    liquidityBurnAddress: string;
    chartUrl: string;
    comments: Array<Comment>;
    treasuryAddress: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<ModuleConfig>;
    buyTax: bigint;
    rewardTokenAddress?: string;
    symbol: string;
    canisterId: Principal;
} {
    return {
        status: from_candid_TokenStatus_n28(_uploadFile, _downloadFile, value.status),
        emblemAspectRatio: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.emblemAspectRatio)),
        popularityScore: value.popularityScore,
        creator: value.creator,
        decimals: value.decimals,
        verified: value.verified,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        fixedTreasuryFee: value.fixedTreasuryFee,
        totalSellTax: value.totalSellTax,
        creatorProfileUrl: value.creatorProfileUrl,
        views: value.views,
        circulatingSupply: value.circulatingSupply,
        deployedAt: value.deployedAt,
        tokenAddress: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.tokenAddress)),
        developerWalletWhitelisted: value.developerWalletWhitelisted,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        trendingScore: value.trendingScore,
        communityExplorer: value.communityExplorer,
        lastUpdated: value.lastUpdated,
        treasuryFee: value.treasuryFee,
        emblemProcessingMetadata: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.emblemProcessingMetadata)),
        description: value.description,
        mintFeePaid: value.mintFeePaid,
        totalSupply: value.totalSupply,
        creatorName: value.creatorName,
        mediaUrl: value.mediaUrl,
        likes: value.likes,
        version: value.version,
        customFields: value.customFields,
        sellTax: value.sellTax,
        validationTimestamp: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.validationTimestamp)),
        testingStatus: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.testingStatus)),
        paymentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.paymentId)),
        totalBuyTax: value.totalBuyTax,
        taxModules: value.taxModules,
        auditStatus: from_candid_AuditStatus_n36(_uploadFile, _downloadFile, value.auditStatus),
        mediaType: from_candid_MediaType_n38(_uploadFile, _downloadFile, value.mediaType),
        liquidityBurnAddress: value.liquidityBurnAddress,
        chartUrl: value.chartUrl,
        comments: value.comments,
        treasuryAddress: value.treasuryAddress,
        aiAgentCompatible: value.aiAgentCompatible,
        moduleConfigs: from_candid_vec_n40(_uploadFile, _downloadFile, value.moduleConfigs),
        buyTax: value.buyTax,
        rewardTokenAddress: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.rewardTokenAddress)),
        symbol: value.symbol,
        canisterId: value.canisterId
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleType: _ModuleType;
    tokenAddress: [] | [string];
    reflectionTarget: [] | [Principal];
    split: boolean;
    sellTax: bigint;
    unified: boolean;
    buyTax: bigint;
    rewardTokenAddress: [] | [string];
}): {
    moduleType: ModuleType;
    tokenAddress?: string;
    reflectionTarget?: Principal;
    split: boolean;
    sellTax: bigint;
    unified: boolean;
    buyTax: bigint;
    rewardTokenAddress?: string;
} {
    return {
        moduleType: from_candid_ModuleType_n43(_uploadFile, _downloadFile, value.moduleType),
        tokenAddress: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.tokenAddress)),
        reflectionTarget: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.reflectionTarget)),
        split: value.split,
        sellTax: value.sellTax,
        unified: value.unified,
        buyTax: value.buyTax,
        rewardTokenAddress: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.rewardTokenAddress))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: boolean;
    usedForToken: boolean;
    treasuryAddressUsed: string;
    errorMessage: [] | [string];
    tokenSymbol: [] | [string];
    timestamp: _Time;
    payer: Principal;
    amount: bigint;
}): {
    verified: boolean;
    usedForToken: boolean;
    treasuryAddressUsed: string;
    errorMessage?: string;
    tokenSymbol?: string;
    timestamp: Time;
    payer: Principal;
    amount: bigint;
} {
    return {
        verified: value.verified,
        usedForToken: value.usedForToken,
        treasuryAddressUsed: value.treasuryAddressUsed,
        errorMessage: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.errorMessage)),
        tokenSymbol: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.tokenSymbol)),
        timestamp: value.timestamp,
        payer: value.payer,
        amount: value.amount
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: {
        message: string;
    };
} | {
    success: {
        message: string;
        canisterId: string;
    };
}): {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
        canisterId: string;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} | {
    archived: null;
}): TokenStatus {
    return "active" in value ? TokenStatus.active : "pending" in value ? TokenStatus.pending : "inactive" in value ? TokenStatus.inactive : "archived" in value ? TokenStatus.archived : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inProgress: null;
} | {
    failed: null;
} | {
    passed: null;
}): TestingStatus {
    return "inProgress" in value ? TestingStatus.inProgress : "failed" in value ? TestingStatus.failed : "passed" in value ? TestingStatus.passed : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    inReview: null;
} | {
    rejected: null;
}): AuditStatus {
    return "pending" in value ? AuditStatus.pending : "approved" in value ? AuditStatus.approved : "inReview" in value ? AuditStatus.inReview : "rejected" in value ? AuditStatus.rejected : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gif: null;
} | {
    audio: null;
} | {
    video: null;
} | {
    image: null;
} | {
    unknown: null;
}): MediaType {
    return "gif" in value ? MediaType.gif : "audio" in value ? MediaType.audio : "video" in value ? MediaType.video : "image" in value ? MediaType.image : "unknown" in value ? MediaType.unknown : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    support: null;
} | {
    burn: null;
} | {
    liquidity: null;
} | {
    reflection: null;
} | {
    yield: null;
} | {
    treasury: null;
}): ModuleType {
    return "support" in value ? ModuleType.support : "burn" in value ? ModuleType.burn : "liquidity" in value ? ModuleType.liquidity : "reflection" in value ? ModuleType.reflection : "yield" in value ? ModuleType.yield : "treasury" in value ? ModuleType.treasury : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n54(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: {
        message: string;
    };
} | {
    success: {
        message: string;
        paymentId: bigint;
    };
}): {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
        paymentId: bigint;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: {
        message: string;
    };
} | {
    success: {
        message: string;
    };
}): {
    __kind__: "error";
    error: {
        message: string;
    };
} | {
    __kind__: "success";
    success: {
        message: string;
    };
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TokenMetadata>): Array<TokenMetadata> {
    return value.map((x)=>from_candid_TokenMetadata_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ModuleConfig>): Array<ModuleConfig> {
    return value.map((x)=>from_candid_ModuleConfig_n41(_uploadFile, _downloadFile, x));
}
function to_candid_AuditStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditStatus): _AuditStatus {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ModuleConfig_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModuleConfig): _ModuleConfig {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_ModuleType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModuleType): _ModuleType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_TestingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestingStatus): _TestingStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_TokenConfig_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenConfig): _TokenConfig {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TokenMetadata_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenMetadata): _TokenMetadata {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_TokenStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenStatus): _TokenStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TokenStatus;
    emblemAspectRatio?: bigint;
    decimals: bigint;
    featured: boolean;
    thumbnailUrl: string;
    creatorProfileUrl: string;
    circulatingSupply: bigint;
    tokenAddress?: string;
    name: string;
    tags: Array<string>;
    communityExplorer: boolean;
    treasuryFee: TreasuryFeeConfig;
    emblemProcessingMetadata?: EmblemProcessingMetadata;
    description: string;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    customFields: Array<CustomField>;
    validationTimestamp?: Time;
    testingStatus?: TestingStatus;
    paymentId?: bigint;
    taxModules: TaxModules;
    mediaType: MediaType;
    chartUrl: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<ModuleConfig>;
    rewardTokenAddress?: string;
    symbol: string;
}): {
    status: _TokenStatus;
    emblemAspectRatio: [] | [bigint];
    decimals: bigint;
    featured: boolean;
    thumbnailUrl: string;
    creatorProfileUrl: string;
    circulatingSupply: bigint;
    tokenAddress: [] | [string];
    name: string;
    tags: Array<string>;
    communityExplorer: boolean;
    treasuryFee: _TreasuryFeeConfig;
    emblemProcessingMetadata: [] | [_EmblemProcessingMetadata];
    description: string;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    customFields: Array<_CustomField>;
    validationTimestamp: [] | [_Time];
    testingStatus: [] | [_TestingStatus];
    paymentId: [] | [bigint];
    taxModules: _TaxModules;
    mediaType: _MediaType;
    chartUrl: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<_ModuleConfig>;
    rewardTokenAddress: [] | [string];
    symbol: string;
} {
    return {
        status: to_candid_TokenStatus_n12(_uploadFile, _downloadFile, value.status),
        emblemAspectRatio: value.emblemAspectRatio ? candid_some(value.emblemAspectRatio) : candid_none(),
        decimals: value.decimals,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        creatorProfileUrl: value.creatorProfileUrl,
        circulatingSupply: value.circulatingSupply,
        tokenAddress: value.tokenAddress ? candid_some(value.tokenAddress) : candid_none(),
        name: value.name,
        tags: value.tags,
        communityExplorer: value.communityExplorer,
        treasuryFee: value.treasuryFee,
        emblemProcessingMetadata: value.emblemProcessingMetadata ? candid_some(value.emblemProcessingMetadata) : candid_none(),
        description: value.description,
        totalSupply: value.totalSupply,
        creatorName: value.creatorName,
        mediaUrl: value.mediaUrl,
        customFields: value.customFields,
        validationTimestamp: value.validationTimestamp ? candid_some(value.validationTimestamp) : candid_none(),
        testingStatus: value.testingStatus ? candid_some(to_candid_TestingStatus_n14(_uploadFile, _downloadFile, value.testingStatus)) : candid_none(),
        paymentId: value.paymentId ? candid_some(value.paymentId) : candid_none(),
        taxModules: value.taxModules,
        mediaType: to_candid_MediaType_n16(_uploadFile, _downloadFile, value.mediaType),
        chartUrl: value.chartUrl,
        aiAgentCompatible: value.aiAgentCompatible,
        moduleConfigs: to_candid_vec_n18(_uploadFile, _downloadFile, value.moduleConfigs),
        rewardTokenAddress: value.rewardTokenAddress ? candid_some(value.rewardTokenAddress) : candid_none(),
        symbol: value.symbol
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleType: ModuleType;
    tokenAddress?: string;
    reflectionTarget?: Principal;
    split: boolean;
    sellTax: bigint;
    unified: boolean;
    buyTax: bigint;
    rewardTokenAddress?: string;
}): {
    moduleType: _ModuleType;
    tokenAddress: [] | [string];
    reflectionTarget: [] | [Principal];
    split: boolean;
    sellTax: bigint;
    unified: boolean;
    buyTax: bigint;
    rewardTokenAddress: [] | [string];
} {
    return {
        moduleType: to_candid_ModuleType_n21(_uploadFile, _downloadFile, value.moduleType),
        tokenAddress: value.tokenAddress ? candid_some(value.tokenAddress) : candid_none(),
        reflectionTarget: value.reflectionTarget ? candid_some(value.reflectionTarget) : candid_none(),
        split: value.split,
        sellTax: value.sellTax,
        unified: value.unified,
        buyTax: value.buyTax,
        rewardTokenAddress: value.rewardTokenAddress ? candid_some(value.rewardTokenAddress) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TokenStatus;
    emblemAspectRatio?: bigint;
    popularityScore: bigint;
    creator: Principal;
    decimals: bigint;
    verified: boolean;
    featured: boolean;
    thumbnailUrl: string;
    fixedTreasuryFee: bigint;
    totalSellTax: bigint;
    creatorProfileUrl: string;
    views: bigint;
    circulatingSupply: bigint;
    deployedAt: Time;
    tokenAddress?: string;
    developerWalletWhitelisted: boolean;
    name: string;
    createdAt: Time;
    tags: Array<string>;
    trendingScore: bigint;
    communityExplorer: boolean;
    lastUpdated: Time;
    treasuryFee: bigint;
    emblemProcessingMetadata?: EmblemProcessingMetadata;
    description: string;
    mintFeePaid: boolean;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    likes: bigint;
    version: bigint;
    customFields: Array<CustomField>;
    sellTax: bigint;
    validationTimestamp?: Time;
    testingStatus?: TestingStatus;
    paymentId?: bigint;
    totalBuyTax: bigint;
    taxModules: TaxModules;
    auditStatus: AuditStatus;
    mediaType: MediaType;
    liquidityBurnAddress: string;
    chartUrl: string;
    comments: Array<Comment>;
    treasuryAddress: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<ModuleConfig>;
    buyTax: bigint;
    rewardTokenAddress?: string;
    symbol: string;
    canisterId: Principal;
}): {
    status: _TokenStatus;
    emblemAspectRatio: [] | [bigint];
    popularityScore: bigint;
    creator: Principal;
    decimals: bigint;
    verified: boolean;
    featured: boolean;
    thumbnailUrl: string;
    fixedTreasuryFee: bigint;
    totalSellTax: bigint;
    creatorProfileUrl: string;
    views: bigint;
    circulatingSupply: bigint;
    deployedAt: _Time;
    tokenAddress: [] | [string];
    developerWalletWhitelisted: boolean;
    name: string;
    createdAt: _Time;
    tags: Array<string>;
    trendingScore: bigint;
    communityExplorer: boolean;
    lastUpdated: _Time;
    treasuryFee: bigint;
    emblemProcessingMetadata: [] | [_EmblemProcessingMetadata];
    description: string;
    mintFeePaid: boolean;
    totalSupply: bigint;
    creatorName: string;
    mediaUrl: string;
    likes: bigint;
    version: bigint;
    customFields: Array<_CustomField>;
    sellTax: bigint;
    validationTimestamp: [] | [_Time];
    testingStatus: [] | [_TestingStatus];
    paymentId: [] | [bigint];
    totalBuyTax: bigint;
    taxModules: _TaxModules;
    auditStatus: _AuditStatus;
    mediaType: _MediaType;
    liquidityBurnAddress: string;
    chartUrl: string;
    comments: Array<_Comment>;
    treasuryAddress: string;
    aiAgentCompatible: boolean;
    moduleConfigs: Array<_ModuleConfig>;
    buyTax: bigint;
    rewardTokenAddress: [] | [string];
    symbol: string;
    canisterId: Principal;
} {
    return {
        status: to_candid_TokenStatus_n12(_uploadFile, _downloadFile, value.status),
        emblemAspectRatio: value.emblemAspectRatio ? candid_some(value.emblemAspectRatio) : candid_none(),
        popularityScore: value.popularityScore,
        creator: value.creator,
        decimals: value.decimals,
        verified: value.verified,
        featured: value.featured,
        thumbnailUrl: value.thumbnailUrl,
        fixedTreasuryFee: value.fixedTreasuryFee,
        totalSellTax: value.totalSellTax,
        creatorProfileUrl: value.creatorProfileUrl,
        views: value.views,
        circulatingSupply: value.circulatingSupply,
        deployedAt: value.deployedAt,
        tokenAddress: value.tokenAddress ? candid_some(value.tokenAddress) : candid_none(),
        developerWalletWhitelisted: value.developerWalletWhitelisted,
        name: value.name,
        createdAt: value.createdAt,
        tags: value.tags,
        trendingScore: value.trendingScore,
        communityExplorer: value.communityExplorer,
        lastUpdated: value.lastUpdated,
        treasuryFee: value.treasuryFee,
        emblemProcessingMetadata: value.emblemProcessingMetadata ? candid_some(value.emblemProcessingMetadata) : candid_none(),
        description: value.description,
        mintFeePaid: value.mintFeePaid,
        totalSupply: value.totalSupply,
        creatorName: value.creatorName,
        mediaUrl: value.mediaUrl,
        likes: value.likes,
        version: value.version,
        customFields: value.customFields,
        sellTax: value.sellTax,
        validationTimestamp: value.validationTimestamp ? candid_some(value.validationTimestamp) : candid_none(),
        testingStatus: value.testingStatus ? candid_some(to_candid_TestingStatus_n14(_uploadFile, _downloadFile, value.testingStatus)) : candid_none(),
        paymentId: value.paymentId ? candid_some(value.paymentId) : candid_none(),
        totalBuyTax: value.totalBuyTax,
        taxModules: value.taxModules,
        auditStatus: to_candid_AuditStatus_n60(_uploadFile, _downloadFile, value.auditStatus),
        mediaType: to_candid_MediaType_n16(_uploadFile, _downloadFile, value.mediaType),
        liquidityBurnAddress: value.liquidityBurnAddress,
        chartUrl: value.chartUrl,
        comments: value.comments,
        treasuryAddress: value.treasuryAddress,
        aiAgentCompatible: value.aiAgentCompatible,
        moduleConfigs: to_candid_vec_n18(_uploadFile, _downloadFile, value.moduleConfigs),
        buyTax: value.buyTax,
        rewardTokenAddress: value.rewardTokenAddress ? candid_some(value.rewardTokenAddress) : candid_none(),
        symbol: value.symbol,
        canisterId: value.canisterId
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenStatus): {
    active: null;
} | {
    pending: null;
} | {
    inactive: null;
} | {
    archived: null;
} {
    return value == TokenStatus.active ? {
        active: null
    } : value == TokenStatus.pending ? {
        pending: null
    } : value == TokenStatus.inactive ? {
        inactive: null
    } : value == TokenStatus.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestingStatus): {
    inProgress: null;
} | {
    failed: null;
} | {
    passed: null;
} {
    return value == TestingStatus.inProgress ? {
        inProgress: null
    } : value == TestingStatus.failed ? {
        failed: null
    } : value == TestingStatus.passed ? {
        passed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    gif: null;
} | {
    audio: null;
} | {
    video: null;
} | {
    image: null;
} | {
    unknown: null;
} {
    return value == MediaType.gif ? {
        gif: null
    } : value == MediaType.audio ? {
        audio: null
    } : value == MediaType.video ? {
        video: null
    } : value == MediaType.image ? {
        image: null
    } : value == MediaType.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModuleType): {
    support: null;
} | {
    burn: null;
} | {
    liquidity: null;
} | {
    reflection: null;
} | {
    yield: null;
} | {
    treasury: null;
} {
    return value == ModuleType.support ? {
        support: null
    } : value == ModuleType.burn ? {
        burn: null
    } : value == ModuleType.liquidity ? {
        liquidity: null
    } : value == ModuleType.reflection ? {
        reflection: null
    } : value == ModuleType.yield ? {
        yield_: null
    } : value == ModuleType.treasury ? {
        treasury: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditStatus): {
    pending: null;
} | {
    approved: null;
} | {
    inReview: null;
} | {
    rejected: null;
} {
    return value == AuditStatus.pending ? {
        pending: null
    } : value == AuditStatus.approved ? {
        approved: null
    } : value == AuditStatus.inReview ? {
        inReview: null
    } : value == AuditStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ModuleConfig>): Array<_ModuleConfig> {
    return value.map((x)=>to_candid_ModuleConfig_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
