/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuditStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'inReview' : null } |
  { 'rejected' : null };
export interface Comment {
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
  'authorProfileUrl' : string,
}
export interface CustomField { 'key' : string, 'value' : string }
export interface EmblemProcessingMetadata {
  'originalWidth' : bigint,
  'cropWidth' : bigint,
  'originalHeight' : bigint,
  'cropX' : bigint,
  'cropY' : bigint,
  'processedAt' : Time,
  'cropHeight' : bigint,
}
export interface GlobalPlatformStats {
  'totalSupplyAcrossTokens' : bigint,
  'totalTokensCreated' : bigint,
  'platformTreasuryFees' : bigint,
  'totalUsers' : bigint,
}
export type MediaType = { 'gif' : null } |
  { 'audio' : null } |
  { 'video' : null } |
  { 'image' : null } |
  { 'unknown' : null };
export interface ModuleConfig {
  'moduleType' : ModuleType,
  'tokenAddress' : [] | [string],
  'reflectionTarget' : [] | [Principal],
  'split' : boolean,
  'sellTax' : bigint,
  'unified' : boolean,
  'buyTax' : bigint,
  'rewardTokenAddress' : [] | [string],
}
export type ModuleType = { 'support' : null } |
  { 'burn' : null } |
  { 'liquidity' : null } |
  { 'reflection' : null } |
  { 'yield' : null } |
  { 'treasury' : null };
export interface PaymentRecord {
  'verified' : boolean,
  'usedForToken' : boolean,
  'treasuryAddressUsed' : string,
  'errorMessage' : [] | [string],
  'tokenSymbol' : [] | [string],
  'timestamp' : Time,
  'payer' : Principal,
  'amount' : bigint,
}
export type PaymentResult = { 'error' : { 'message' : string } } |
  { 'success' : { 'message' : string, 'paymentId' : bigint } };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TaxModules {
  'support' : boolean,
  'burn' : boolean,
  'liquidity' : boolean,
  'reflection' : boolean,
  'yield' : boolean,
  'treasury' : boolean,
}
export type TestingStatus = { 'inProgress' : null } |
  { 'failed' : null } |
  { 'passed' : null };
export type Time = bigint;
export interface TokenConfig {
  'status' : TokenStatus,
  'emblemAspectRatio' : [] | [bigint],
  'decimals' : bigint,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'creatorProfileUrl' : string,
  'circulatingSupply' : bigint,
  'tokenAddress' : [] | [string],
  'name' : string,
  'tags' : Array<string>,
  'communityExplorer' : boolean,
  'treasuryFee' : TreasuryFeeConfig,
  'emblemProcessingMetadata' : [] | [EmblemProcessingMetadata],
  'description' : string,
  'totalSupply' : bigint,
  'creatorName' : string,
  'mediaUrl' : string,
  'customFields' : Array<CustomField>,
  'validationTimestamp' : [] | [Time],
  'testingStatus' : [] | [TestingStatus],
  'paymentId' : [] | [bigint],
  'taxModules' : TaxModules,
  'mediaType' : MediaType,
  'chartUrl' : string,
  'aiAgentCompatible' : boolean,
  'moduleConfigs' : Array<ModuleConfig>,
  'rewardTokenAddress' : [] | [string],
  'symbol' : string,
}
export type TokenCreationResult = { 'error' : { 'message' : string } } |
  { 'success' : { 'message' : string, 'canisterId' : string } };
export interface TokenMetadata {
  'status' : TokenStatus,
  'emblemAspectRatio' : [] | [bigint],
  'popularityScore' : bigint,
  'creator' : Principal,
  'decimals' : bigint,
  'verified' : boolean,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'fixedTreasuryFee' : bigint,
  'totalSellTax' : bigint,
  'creatorProfileUrl' : string,
  'views' : bigint,
  'circulatingSupply' : bigint,
  'deployedAt' : Time,
  'tokenAddress' : [] | [string],
  'developerWalletWhitelisted' : boolean,
  'name' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'trendingScore' : bigint,
  'communityExplorer' : boolean,
  'lastUpdated' : Time,
  'treasuryFee' : bigint,
  'emblemProcessingMetadata' : [] | [EmblemProcessingMetadata],
  'description' : string,
  'mintFeePaid' : boolean,
  'totalSupply' : bigint,
  'creatorName' : string,
  'mediaUrl' : string,
  'likes' : bigint,
  'version' : bigint,
  'customFields' : Array<CustomField>,
  'sellTax' : bigint,
  'validationTimestamp' : [] | [Time],
  'testingStatus' : [] | [TestingStatus],
  'paymentId' : [] | [bigint],
  'totalBuyTax' : bigint,
  'taxModules' : TaxModules,
  'auditStatus' : AuditStatus,
  'mediaType' : MediaType,
  'liquidityBurnAddress' : string,
  'chartUrl' : string,
  'comments' : Array<Comment>,
  'treasuryAddress' : string,
  'aiAgentCompatible' : boolean,
  'moduleConfigs' : Array<ModuleConfig>,
  'buyTax' : bigint,
  'rewardTokenAddress' : [] | [string],
  'symbol' : string,
  'canisterId' : Principal,
}
export type TokenStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null } |
  { 'archived' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TreasuryFeeConfig {
  'enabled' : boolean,
  'sellFee' : bigint,
  'treasuryAddress' : string,
  'buyFee' : bigint,
}
export interface UserActivityMetrics {
  'tokensMinted' : bigint,
  'totalFeesPaid' : bigint,
  'treasuryConfigurations' : bigint,
  'deploymentHistory' : Array<string>,
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'email' : string,
  'linkedPrincipals' : Array<Principal>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VerifyPaymentResult = { 'error' : { 'message' : string } } |
  { 'success' : { 'message' : string } };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createToken' : ActorMethod<[TokenConfig], TokenCreationResult>,
  'getAllTokens' : ActorMethod<[], Array<TokenMetadata>>,
  'getBuyMeACoffeeAddress' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreationFee' : ActorMethod<[], bigint>,
  'getForgedTokens' : ActorMethod<[], Array<TokenMetadata>>,
  'getGlobalPlatformStats' : ActorMethod<[], GlobalPlatformStats>,
  'getPaymentRecord' : ActorMethod<[bigint], [] | [PaymentRecord]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getToken' : ActorMethod<[string], [] | [TokenMetadata]>,
  'getTokenCount' : ActorMethod<[], bigint>,
  'getTreasuryAddress' : ActorMethod<[], string>,
  'getUserActivityMetrics' : ActorMethod<[], UserActivityMetrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'lookupToken' : ActorMethod<[string], [] | [TokenMetadata]>,
  'markMintFeePaid' : ActorMethod<[string, bigint], undefined>,
  'recordPayment' : ActorMethod<[bigint, string], PaymentResult>,
  'registerToken' : ActorMethod<[TokenMetadata], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyPaymentWithLedger' : ActorMethod<
    [string, bigint],
    VerifyPaymentResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];