/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TokenStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
  'archived' : IDL.Null,
});
export const TreasuryFeeConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'sellFee' : IDL.Nat,
  'treasuryAddress' : IDL.Text,
  'buyFee' : IDL.Nat,
});
export const Time = IDL.Int;
export const EmblemProcessingMetadata = IDL.Record({
  'originalWidth' : IDL.Nat,
  'cropWidth' : IDL.Nat,
  'originalHeight' : IDL.Nat,
  'cropX' : IDL.Nat,
  'cropY' : IDL.Nat,
  'processedAt' : Time,
  'cropHeight' : IDL.Nat,
});
export const CustomField = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const TestingStatus = IDL.Variant({
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
  'passed' : IDL.Null,
});
export const TaxModules = IDL.Record({
  'support' : IDL.Bool,
  'burn' : IDL.Bool,
  'liquidity' : IDL.Bool,
  'reflection' : IDL.Bool,
  'yield' : IDL.Bool,
  'treasury' : IDL.Bool,
});
export const MediaType = IDL.Variant({
  'gif' : IDL.Null,
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'image' : IDL.Null,
  'unknown' : IDL.Null,
});
export const ModuleType = IDL.Variant({
  'support' : IDL.Null,
  'burn' : IDL.Null,
  'liquidity' : IDL.Null,
  'reflection' : IDL.Null,
  'yield' : IDL.Null,
  'treasury' : IDL.Null,
});
export const ModuleConfig = IDL.Record({
  'moduleType' : ModuleType,
  'tokenAddress' : IDL.Opt(IDL.Text),
  'reflectionTarget' : IDL.Opt(IDL.Principal),
  'split' : IDL.Bool,
  'sellTax' : IDL.Nat,
  'unified' : IDL.Bool,
  'buyTax' : IDL.Nat,
  'rewardTokenAddress' : IDL.Opt(IDL.Text),
});
export const TokenConfig = IDL.Record({
  'status' : TokenStatus,
  'emblemAspectRatio' : IDL.Opt(IDL.Nat),
  'decimals' : IDL.Nat,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'creatorProfileUrl' : IDL.Text,
  'circulatingSupply' : IDL.Nat,
  'tokenAddress' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'communityExplorer' : IDL.Bool,
  'treasuryFee' : TreasuryFeeConfig,
  'emblemProcessingMetadata' : IDL.Opt(EmblemProcessingMetadata),
  'description' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'creatorName' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'customFields' : IDL.Vec(CustomField),
  'validationTimestamp' : IDL.Opt(Time),
  'testingStatus' : IDL.Opt(TestingStatus),
  'paymentId' : IDL.Opt(IDL.Nat),
  'taxModules' : TaxModules,
  'mediaType' : MediaType,
  'chartUrl' : IDL.Text,
  'aiAgentCompatible' : IDL.Bool,
  'moduleConfigs' : IDL.Vec(ModuleConfig),
  'rewardTokenAddress' : IDL.Opt(IDL.Text),
  'symbol' : IDL.Text,
});
export const TokenCreationResult = IDL.Variant({
  'error' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'message' : IDL.Text, 'canisterId' : IDL.Text }),
});
export const AuditStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'inReview' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'authorProfileUrl' : IDL.Text,
});
export const TokenMetadata = IDL.Record({
  'status' : TokenStatus,
  'emblemAspectRatio' : IDL.Opt(IDL.Nat),
  'popularityScore' : IDL.Nat,
  'creator' : IDL.Principal,
  'decimals' : IDL.Nat,
  'verified' : IDL.Bool,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'fixedTreasuryFee' : IDL.Nat,
  'totalSellTax' : IDL.Nat,
  'creatorProfileUrl' : IDL.Text,
  'views' : IDL.Nat,
  'circulatingSupply' : IDL.Nat,
  'deployedAt' : Time,
  'tokenAddress' : IDL.Opt(IDL.Text),
  'developerWalletWhitelisted' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'trendingScore' : IDL.Nat,
  'communityExplorer' : IDL.Bool,
  'lastUpdated' : Time,
  'treasuryFee' : IDL.Nat,
  'emblemProcessingMetadata' : IDL.Opt(EmblemProcessingMetadata),
  'description' : IDL.Text,
  'mintFeePaid' : IDL.Bool,
  'totalSupply' : IDL.Nat,
  'creatorName' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'likes' : IDL.Nat,
  'version' : IDL.Nat,
  'customFields' : IDL.Vec(CustomField),
  'sellTax' : IDL.Nat,
  'validationTimestamp' : IDL.Opt(Time),
  'testingStatus' : IDL.Opt(TestingStatus),
  'paymentId' : IDL.Opt(IDL.Nat),
  'totalBuyTax' : IDL.Nat,
  'taxModules' : TaxModules,
  'auditStatus' : AuditStatus,
  'mediaType' : MediaType,
  'liquidityBurnAddress' : IDL.Text,
  'chartUrl' : IDL.Text,
  'comments' : IDL.Vec(Comment),
  'treasuryAddress' : IDL.Text,
  'aiAgentCompatible' : IDL.Bool,
  'moduleConfigs' : IDL.Vec(ModuleConfig),
  'buyTax' : IDL.Nat,
  'rewardTokenAddress' : IDL.Opt(IDL.Text),
  'symbol' : IDL.Text,
  'canisterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'linkedPrincipals' : IDL.Vec(IDL.Principal),
});
export const GlobalPlatformStats = IDL.Record({
  'totalSupplyAcrossTokens' : IDL.Nat,
  'totalTokensCreated' : IDL.Nat,
  'platformTreasuryFees' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'verified' : IDL.Bool,
  'usedForToken' : IDL.Bool,
  'treasuryAddressUsed' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'tokenSymbol' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'payer' : IDL.Principal,
  'amount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const UserActivityMetrics = IDL.Record({
  'tokensMinted' : IDL.Nat,
  'totalFeesPaid' : IDL.Nat,
  'treasuryConfigurations' : IDL.Nat,
  'deploymentHistory' : IDL.Vec(IDL.Text),
});
export const PaymentResult = IDL.Variant({
  'error' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'message' : IDL.Text, 'paymentId' : IDL.Nat }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const VerifyPaymentResult = IDL.Variant({
  'error' : IDL.Record({ 'message' : IDL.Text }),
  'success' : IDL.Record({ 'message' : IDL.Text }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createToken' : IDL.Func([TokenConfig], [TokenCreationResult], []),
  'getAllTokens' : IDL.Func([], [IDL.Vec(TokenMetadata)], ['query']),
  'getBuyMeACoffeeAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreationFee' : IDL.Func([], [IDL.Nat], ['query']),
  'getForgedTokens' : IDL.Func([], [IDL.Vec(TokenMetadata)], ['query']),
  'getGlobalPlatformStats' : IDL.Func([], [GlobalPlatformStats], ['query']),
  'getPaymentRecord' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentRecord)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getToken' : IDL.Func([IDL.Text], [IDL.Opt(TokenMetadata)], ['query']),
  'getTokenCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTreasuryAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getUserActivityMetrics' : IDL.Func([], [UserActivityMetrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'lookupToken' : IDL.Func([IDL.Text], [IDL.Opt(TokenMetadata)], ['query']),
  'markMintFeePaid' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'recordPayment' : IDL.Func([IDL.Nat, IDL.Text], [PaymentResult], []),
  'registerToken' : IDL.Func([TokenMetadata], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'verifyPaymentWithLedger' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [VerifyPaymentResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TokenStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
    'archived' : IDL.Null,
  });
  const TreasuryFeeConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'sellFee' : IDL.Nat,
    'treasuryAddress' : IDL.Text,
    'buyFee' : IDL.Nat,
  });
  const Time = IDL.Int;
  const EmblemProcessingMetadata = IDL.Record({
    'originalWidth' : IDL.Nat,
    'cropWidth' : IDL.Nat,
    'originalHeight' : IDL.Nat,
    'cropX' : IDL.Nat,
    'cropY' : IDL.Nat,
    'processedAt' : Time,
    'cropHeight' : IDL.Nat,
  });
  const CustomField = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const TestingStatus = IDL.Variant({
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
    'passed' : IDL.Null,
  });
  const TaxModules = IDL.Record({
    'support' : IDL.Bool,
    'burn' : IDL.Bool,
    'liquidity' : IDL.Bool,
    'reflection' : IDL.Bool,
    'yield' : IDL.Bool,
    'treasury' : IDL.Bool,
  });
  const MediaType = IDL.Variant({
    'gif' : IDL.Null,
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'image' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const ModuleType = IDL.Variant({
    'support' : IDL.Null,
    'burn' : IDL.Null,
    'liquidity' : IDL.Null,
    'reflection' : IDL.Null,
    'yield' : IDL.Null,
    'treasury' : IDL.Null,
  });
  const ModuleConfig = IDL.Record({
    'moduleType' : ModuleType,
    'tokenAddress' : IDL.Opt(IDL.Text),
    'reflectionTarget' : IDL.Opt(IDL.Principal),
    'split' : IDL.Bool,
    'sellTax' : IDL.Nat,
    'unified' : IDL.Bool,
    'buyTax' : IDL.Nat,
    'rewardTokenAddress' : IDL.Opt(IDL.Text),
  });
  const TokenConfig = IDL.Record({
    'status' : TokenStatus,
    'emblemAspectRatio' : IDL.Opt(IDL.Nat),
    'decimals' : IDL.Nat,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'creatorProfileUrl' : IDL.Text,
    'circulatingSupply' : IDL.Nat,
    'tokenAddress' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'communityExplorer' : IDL.Bool,
    'treasuryFee' : TreasuryFeeConfig,
    'emblemProcessingMetadata' : IDL.Opt(EmblemProcessingMetadata),
    'description' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'creatorName' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'customFields' : IDL.Vec(CustomField),
    'validationTimestamp' : IDL.Opt(Time),
    'testingStatus' : IDL.Opt(TestingStatus),
    'paymentId' : IDL.Opt(IDL.Nat),
    'taxModules' : TaxModules,
    'mediaType' : MediaType,
    'chartUrl' : IDL.Text,
    'aiAgentCompatible' : IDL.Bool,
    'moduleConfigs' : IDL.Vec(ModuleConfig),
    'rewardTokenAddress' : IDL.Opt(IDL.Text),
    'symbol' : IDL.Text,
  });
  const TokenCreationResult = IDL.Variant({
    'error' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'message' : IDL.Text, 'canisterId' : IDL.Text }),
  });
  const AuditStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'inReview' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'authorProfileUrl' : IDL.Text,
  });
  const TokenMetadata = IDL.Record({
    'status' : TokenStatus,
    'emblemAspectRatio' : IDL.Opt(IDL.Nat),
    'popularityScore' : IDL.Nat,
    'creator' : IDL.Principal,
    'decimals' : IDL.Nat,
    'verified' : IDL.Bool,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'fixedTreasuryFee' : IDL.Nat,
    'totalSellTax' : IDL.Nat,
    'creatorProfileUrl' : IDL.Text,
    'views' : IDL.Nat,
    'circulatingSupply' : IDL.Nat,
    'deployedAt' : Time,
    'tokenAddress' : IDL.Opt(IDL.Text),
    'developerWalletWhitelisted' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'trendingScore' : IDL.Nat,
    'communityExplorer' : IDL.Bool,
    'lastUpdated' : Time,
    'treasuryFee' : IDL.Nat,
    'emblemProcessingMetadata' : IDL.Opt(EmblemProcessingMetadata),
    'description' : IDL.Text,
    'mintFeePaid' : IDL.Bool,
    'totalSupply' : IDL.Nat,
    'creatorName' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'likes' : IDL.Nat,
    'version' : IDL.Nat,
    'customFields' : IDL.Vec(CustomField),
    'sellTax' : IDL.Nat,
    'validationTimestamp' : IDL.Opt(Time),
    'testingStatus' : IDL.Opt(TestingStatus),
    'paymentId' : IDL.Opt(IDL.Nat),
    'totalBuyTax' : IDL.Nat,
    'taxModules' : TaxModules,
    'auditStatus' : AuditStatus,
    'mediaType' : MediaType,
    'liquidityBurnAddress' : IDL.Text,
    'chartUrl' : IDL.Text,
    'comments' : IDL.Vec(Comment),
    'treasuryAddress' : IDL.Text,
    'aiAgentCompatible' : IDL.Bool,
    'moduleConfigs' : IDL.Vec(ModuleConfig),
    'buyTax' : IDL.Nat,
    'rewardTokenAddress' : IDL.Opt(IDL.Text),
    'symbol' : IDL.Text,
    'canisterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'linkedPrincipals' : IDL.Vec(IDL.Principal),
  });
  const GlobalPlatformStats = IDL.Record({
    'totalSupplyAcrossTokens' : IDL.Nat,
    'totalTokensCreated' : IDL.Nat,
    'platformTreasuryFees' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'verified' : IDL.Bool,
    'usedForToken' : IDL.Bool,
    'treasuryAddressUsed' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'tokenSymbol' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const UserActivityMetrics = IDL.Record({
    'tokensMinted' : IDL.Nat,
    'totalFeesPaid' : IDL.Nat,
    'treasuryConfigurations' : IDL.Nat,
    'deploymentHistory' : IDL.Vec(IDL.Text),
  });
  const PaymentResult = IDL.Variant({
    'error' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'message' : IDL.Text, 'paymentId' : IDL.Nat }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const VerifyPaymentResult = IDL.Variant({
    'error' : IDL.Record({ 'message' : IDL.Text }),
    'success' : IDL.Record({ 'message' : IDL.Text }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createToken' : IDL.Func([TokenConfig], [TokenCreationResult], []),
    'getAllTokens' : IDL.Func([], [IDL.Vec(TokenMetadata)], ['query']),
    'getBuyMeACoffeeAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreationFee' : IDL.Func([], [IDL.Nat], ['query']),
    'getForgedTokens' : IDL.Func([], [IDL.Vec(TokenMetadata)], ['query']),
    'getGlobalPlatformStats' : IDL.Func([], [GlobalPlatformStats], ['query']),
    'getPaymentRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentRecord)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getToken' : IDL.Func([IDL.Text], [IDL.Opt(TokenMetadata)], ['query']),
    'getTokenCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreasuryAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getUserActivityMetrics' : IDL.Func([], [UserActivityMetrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'lookupToken' : IDL.Func([IDL.Text], [IDL.Opt(TokenMetadata)], ['query']),
    'markMintFeePaid' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'recordPayment' : IDL.Func([IDL.Nat, IDL.Text], [PaymentResult], []),
    'registerToken' : IDL.Func([TokenMetadata], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'verifyPaymentWithLedger' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [VerifyPaymentResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };